name: game_launcher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  english_words: ^4.0.0
  sensors_plus: ^6.1.0
  shared_preferences: ^2.2.0
  wakelock_plus: ^1.2.10
  double_back_to_close_app: ^2.0.0
  syncfusion_flutter_gauges: ^28.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  

  assets:
    - assets/images/dice-1.png
    - assets/images/dice-2.png
    - assets/images/dice-3.png
    - assets/images/dice-4.png
    - assets/images/dice-5.png
    - assets/images/dice-6.png
    - assets/images/GameDefault.png
    - assets/images/paper.JPG
    - assets/images/rock.JPG
    - assets/images/scissors.JPG
    - assets/images/intro_screen.webp
    - lib/l10n/

